config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  resources :items, only: [:index, :show, :new, :create, :update, :destroy] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:show, :destroy] do
    member do
      post :accept
      post :reject
    end
  end

  get "/my_booked_items/:id", to: "bookings#booked_items_show", as: :my_booked_item

  get "/dashboard", to: "bookings#dashboard"

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_item, only: [:create]

  def create
    @booking = Booking.new(booking_params)
    @booking.status = "Pending"
    @booking.item = @item
    @booking.user = current_user
    @booking.total_price = ((@booking.end_date - @booking.start_date) / 86400 ) * @item.price
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def dashboard
    @my_items = current_user.items
    @my_bookings = current_user.bookings
    @all_bookings = Booking.includes(item: :user)
    @item = Item.new
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to item_path(@booking.item), status: :see_other
  end

  def booked_items_show
    @booking = Booking.find(params[:id])
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "Accepted")
    redirect_to my_booked_item_path(@booking), notice: "Status updated to #{@booking.status}"
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.update(status: "Rejected")
    redirect_to my_booked_item_path(@booking), notice: "Status updated to #{@booking.status}"
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/views/bookings/_confirm_booking_modal.html.erb
<div class="modal fade" id="confirmBookedItemModal" tabindex="-1" aria-labelledby="confirmBookedItemModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="confirmBookedItemModalLabel">Accept booking request</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>You are going to accept <strong><%= @booking.user.first_name %> <%= @booking.user.last_name %></strong>'s booking request.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="blue-button" data-bs-dismiss="modal">Close</button>
        <%= link_to 'Accept booking', accept_booking_path(@booking), data: {turbo_method: :post}, class:"red-button accept-button" %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<div data-controller="modal">
<%= simple_form_for [item, booking], data: { controller: "datepicker" } do |f| %>
  <%= f.input :start_date,
              as: :string,
              input_html: { data: { datepicker_target: "startDate", modal_target: "start" } }
               %>
  <%= f.input :end_date,
              as: :string,
              input_html: { data: { datepicker_target: "endDate", modal_target: "end" } } %>
  <input type="hidden" value="<%= @item.price %>" data-modal-target="dayprice">
  <button type="button" class="red-button" data-bs-toggle="modal" data-bs-target="#bookingModal" data-action="click->modal#click">
    Book now
  </button>
  <%= render 'bookings/remote_modal', booking: booking %>
<% end %>
</div>

app/views/bookings/_reject_booking_modal.html.erb
<div class="modal fade" id="rejectBookedItemModal" tabindex="-1" aria-labelledby="rejectBookedItemModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="rejectBookedItemModalLabel">Decline booking request</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>You are going to decline <%= @booking.user.first_name %> <%= @booking.user.last_name %>'s booking request</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="blue-button" data-bs-dismiss="modal">Close</button>
        <%= link_to 'Reject booking', reject_booking_path(@booking), data: {turbo_method: :post}, class:"red-button reject-button" %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_remote_modal.html.erb
<div class="modal fade" id="bookingModal" tabindex="-1" aria-labelledby="bookingModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 color-blue" id="bookingModalLabel">Book <%= @item.title %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Your booking request will be sent to <%= @item.user.first_name %> <%= @item.user.last_name %></p>
        <p><u>Total cost for the selected period:</u></p>
        <p data-modal-target="totalprice"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="blue-button" data-bs-dismiss="modal">Close</button>
        <input type="submit" class="red-button" value="Confirm booking">
      </div>
    </div>
  </div>
</div>

app/views/bookings/booked_items_show.html.erb
<div class="container">
  <div class="row m-4 justify-content-center">
    <h1 class="mb-5 text-center color-blue">My booking request details</h1>
      <div class="col-6">
          <% if @booking.item.user == current_user %>
            <div class="card mb-5 shadow-sm booking-container">
              <div class="card-img-top image-container-booking border-bottom">
                <% @booking.item.photos.each do |photo| %>
                <%= cl_image_tag photo.key, id: "custom-img", crop: :fill %>
                <% end %>
              </div>
              <div class="card-body p-0">
                <div class="card-header p-0">
                  <h5 class="card-title p-3 m-0 bg-primary text-white"><strong><%= @booking.item.title %></strong></h5>
                </div>
                <ul class="list-group list-group-flush border-bottom">
                  <li class="list-group-item bg-white">Artwork description: <%= @booking.item.description %></li>
                  <li class="list-group-item bg-white">Artwork category: <%= @booking.item.category %></li>
                  <li class="list-group-item bg-white">Artist: <%= @booking.item.artist %></li>
                  <li class="list-group-item bg-white">Artwork location: <%= @booking.item.address %></li>
                </ul>
                <div class="card-header bg-primary text-white"><strong>Booking details</strong></div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item bg-white">Requestor name: <%= @booking.user.first_name %> <%= @booking.user.last_name %></li>
                  <li class="list-group-item bg-white">Start date: <%= @booking.start_date.strftime("%d/%m/%Y") %></li>
                  <li class="list-group-item bg-white">End date: <%= @booking.end_date.strftime("%d/%m/%Y") %></li>
                  <% if @booking.status == "Pending" %>
                    <li class="list-group-item bg-white color-pending">Status: <strong><%= @booking.status %></strong></li>
                  <% elsif @booking.status == "Accepted" %>
                    <li class="list-group-item bg-white color-accepted">Status: <strong><%= @booking.status %></strong></li>
                  <% elsif @booking.status == "Rejected" %>
                    <li class="list-group-item bg-white color-rejected">Status: <strong><%= @booking.status %></strong></li>
                  <% end %>
                  <li class="list-group-item bg-white">Booking total price: <i class="fa-solid fa-euro-sign"></i> <%= @booking.total_price.round() %></li>
                </ul>
                <% if @booking.status == "Pending" %>
                  <div class="bg-white d-flex border">
                    <%= link_to 'Accept', accept_booking_path(@booking), class:"btn accept-button text-white flex-grow-1",
                    data: { bs_toggle: "modal", bs_target: "#confirmBookedItemModal" } %>
                    <%= link_to 'Reject', reject_booking_path(@booking), class:"btn reject-button text-white flex-grow-1",
                    data: { bs_toggle: "modal", bs_target: "#rejectBookedItemModal" } %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <%= render 'bookings/confirm_booking_modal', booking: @booking %>
        <%= render 'bookings/reject_booking_modal', booking: @booking %>
        <a class="blue-button" href="/dashboard#booked-items-tab">Back</a>
      </div>
  </div>
</div>

app/views/bookings/dashboard.html.erb
<div class="row my-3">
  <div style="width: 550px" class="flex ps-0 pb-2 thick-underline mb-5">
    <h1 class="m-0 color-blue p-0 inline"><%= current_user.first_name %>'s dashboard</h1>
  </div>

      <%# Tab titles %>

      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="items-tab" data-bs-toggle="tab" data-bs-target="#items-tab-pane" type="button" role="tab" aria-controls="items-tab-pane" aria-selected="true">My items</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="bookings-tab" data-bs-toggle="tab" data-bs-target="#bookings-tab-pane" type="button" role="tab" aria-controls="bookings-tab-pane" aria-selected="false">My bookings</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="booked-items-tab" data-bs-toggle="tab" data-bs-target="#booked-items-tab-pane" type="button" role="tab" aria-controls="booked-items-tab-pane" aria-selected="false">My booking requests</button>
        </li>
      </ul>

      <div class="tab-content p-0" id="myTabContent">

        <%# First tab: User's items - items owned by user %>

        <div class="tab-pane fade show active" id="items-tab-pane" role="tabpanel" aria-labelledby="items-tab" tabindex="0">
          <div class="mt-4">

            <h2 class="color-blue mb-3">My Items</h2>

            <button type="button" class="red-button mb-4" data-bs-toggle="modal" data-bs-target="#addItemModal">
              Add an item
            </button>

                <div class="modal fade" id="addItemModal" tabindex="-1" aria-labelledby="addItemModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="addItemModalLabel">Add a new item</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <%= render "items/form", item: @item %>
                      </div>
                    </div>
                  </div>
                </div>

              <% if @my_items.any? %>
                <div class="my-items-grid">
                  <% @my_items.each do |item| %>
                  <%= link_to item do %>
                    <div class="my-item-card mt-3" style="background-image: url(<%= cl_image_path item.photos.first.key, crop: :fill %>)">
                      <div class="content-card">
                        <div class="my-item-card-title">
                          <h3 class="m-0"><%= item.title %></h3>
                        </div>
                        <div class="my-item-card-description">
                        </div>
                      </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
            <% else %>
              <p class="filler">You don't have any items yet.</p>
            <% end %>
          </div>
        </div>

        <%# Second tab: User's bookings - bookings made by user %>

        <div class="tab-pane fade" id="bookings-tab-pane" role="tabpanel" aria-labelledby="bookings-tab" tabindex="0">
          <div class="mt-4">
            <%# Checking if the current user made bookings %>
            <%# If this is the case, normal display. If there are no bookings to display, display a large bottom padding so that container displays properly on top of the page %>
            <% if current_user.bookings.any? %>
              <h2 class="my-4 color-blue">My bookings</h2>
            <% else %>
              <h2 class="my-4 color-blue filler">My bookings</h2>
            <% end %>
            <div class="cards">
                <%# <div class="col-6"> %>
                  <% @my_bookings.each do |booking| %>
                    <%= link_to booking_path(booking) do %>
                      <div class="card shadow-sm">
                        <div class="card-img-top image-container-booking border-bottom">
                          <% booking.item.photos.each do |photo| %>
                          <%= cl_image_tag photo.key, class: "custom-bookindex-img", crop: :fill %>
                          <% end %>
                        </div>
                        <div class="card-body p-0 bg-light">
                          <h5 class="card-title p-3 m-0 border-bottom bg-primary text-white"><strong><%=  booking.item.title %></strong></h5>
                          <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-white color-blue"><i class="fa-solid fa-calendar-days"></i> <%= booking.start_date.strftime("%d/%m/%Y") %></li>
                            <li class="list-group-item bg-white color-blue"><i class="fa-solid fa-calendar-days"></i> <%= booking.end_date.strftime("%d/%m/%Y") %></li>
                            <li class="list-group-item bg-white color-blue"><i class="fa-solid fa-tag"></i> <%= booking.total_price.round() %> <i class="fa-solid fa-euro-sign"></i> </li>
                            <% if booking.status == "Pending" %>
                              <li class="list-group-item bg-white color-pending"><i class="fa-solid fa-bars-progress color-blue"></i> <strong><%= booking.status %></strong></li>
                            <% elsif booking.status == "Accepted" %>
                              <li class="list-group-item bg-white color-accepted"><i class="fa-solid fa-bars-progress color-blue"></i> <strong><%= booking.status %></strong></li>
                            <% elsif booking.status == "Rejected" %>
                              <li class="list-group-item bg-white color-rejected"><i class="fa-solid fa-bars-progress color-blue"></i> <strong><%= booking.status %></strong></li>
                            <% end %>
                          </ul>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                <%# </div> %>
            </div>
          </div>
        </div>

        <%# Third tab: User's booked items - Booking requests received by user %>

        <div class="tab-pane fade" id="booked-items-tab-pane" role="tabpanel" aria-labelledby="booked-items-tab" tabindex="0">

            <div class="mt-4">
              <%# Checking if someone booked one if the items of the current user %>
              <%# If this is the case, normal display. If there are no booked items to display, display a large bottom padding so that container displays properly on top of the page %>
              <% if (@all_bookings.map { |booking| booking.item.user.id }.include?(current_user.id)) %>
                <h2 class="my-4 color-blue">My booking requests</h2>
              <% else %>
                <h2 class="my-4 color-blue filler">My booking requests</h2>
              <% end %>
              <div class="cards">
                <% @all_bookings.each do |booking| %>
                  <% if booking.item.user == current_user %>
                    <%= link_to my_booked_item_path(booking) do %>
                      <div class="card shadow-sm mb-4">
                        <div class="card-img-top image-container-booking border-bottom">
                          <% booking.item.photos.each do |photo| %>
                            <%= cl_image_tag photo.key, class: "custom-bookindex-img", crop: :fill %>
                          <% end %>
                        </div>
                        <div class="card-body p-0 bg-light">
                          <h5 class="card-title p-3 m-0 border-bottom bg-primary text-white"><strong><%= booking.item.title %></strong></h5>
                          <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-white"><i class="fa-solid fa-user"></i> <%= booking.user.first_name %> <%= booking.user.last_name %></li>
                            <li class="list-group-item bg-white"><i class="fa-solid fa-calendar-days"></i> <%= booking.start_date.strftime("%d/%m/%Y") %></li>
                            <li class="list-group-item bg-white"><i class="fa-solid fa-calendar-days"></i> <%= booking.end_date.strftime("%d/%m/%Y") %></li>
                            <li class="list-group-item bg-white"><i class="fa-solid fa-tag"></i> <%= booking.total_price.round %> <i class="fa-solid fa-euro-sign"></i> </li>
                            <% if booking.status == "Pending" %>
                              <li class="list-group-item bg-white color-pending"><i class="fa-solid fa-bars-progress color-blue"></i> <strong><%= booking.status %></strong></li>
                            <% elsif booking.status == "Accepted" %>
                              <li class="list-group-item bg-white color-accepted"><i class="fa-solid fa-bars-progress color-blue"></i> <strong><%= booking.status %></strong></li>
                            <% elsif booking.status == "Rejected" %>
                              <li class="list-group-item bg-white color-rejected"><i class="fa-solid fa-bars-progress color-blue"></i> <strong><%= booking.status %></strong></li>
                            <% end %>
                          </ul>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
        </div>
      </div>
</div>

<%= javascript_include_tag 'custom/tab_history.js' %>
<%= javascript_include_tag 'custom/tab_redirection.js' %>

app/views/bookings/my_booked_items.html.erb
<div class="row m-4">
  <h1 class="mb-3">My bookings</h1>
    <div class="col-6">
      <% @booked_items.each do |booked_item| %>
        <div class="card mb-4">
          <img class="card-img-top" src="..." alt="Item image">
          <div class="card-body">
            <div class="card-header">
              <h5 class="card-title"><strong><%= booked_item.title %></strong></h5>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Description de l'oeuvre: <%= booked_item.description %></li>
              <li class="list-group-item">Catégorie de l'oeuvre: <%= booked_item.category %></li>
              <li class="list-group-item">Artiste: <%= booked_item.artist %></li>
              <li class="list-group-item">Emplacement de l'oeuvre: <%= booked_item.address %></li>
            </ul>
            <div class="card-header">Propriétaire</div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Nom: <%= current_user.first_name %> <%= current_user.last_name %></li>
            </ul>
            <div class="card-header">Réservations</div>
            <%= booked_items.bookings each |booking| %>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Date de départ: <%= booked_item.booking.start_date %></li>
                <li class="list-group-item">Date de fin: <%= booked_item.booking.end_date %></li>
                <li class="list-group-item">Prix total de la réservation: <i class="fa-solid fa-euro-sign"></i> <%= booked_item.booking.total_price %></li>
              </ul>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row m-4 justify-content-center">
    <h1 class="mb-4 text-center color-blue">My booking details</h1>
      <div class="col-6">
          <div class="card mb-5 shadow-sm booking-container">
            <div class="card-img-top image-container-booking border-bottom">
              <% @booking.item.photos.each do |photo| %>
              <%= cl_image_tag photo.key, id: "custom-bookshow-img", crop: :fill %>
              <% end %>
            </div>
            <div class="card-body p-0">
              <div class="card-header p-0">
                <h5 class="card-title p-3 m-0 bg-primary text-white"><strong><%= @booking.item.title %></strong></h5>
              </div>
              <ul class="list-group list-group-flush border-bottom">
                <li class="list-group-item bg-white">Artwork description: <%= @booking.item.description %></li>
                <li class="list-group-item bg-white">Artwork category: <%= @booking.item.category %></li>
                <li class="list-group-item bg-white">Artist: <%= @booking.item.artist %></li>
                <li class="list-group-item bg-white">Artwork location: <%= @booking.item.address %></li>
              </ul>
              <div class="card-header bg-primary text-white"><strong>Owner</strong></div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item bg-white">Name: <%= @booking.item.user.first_name %> <%= @booking.item.user.last_name %></li>
              </ul>
              <div class="card-header bg-primary text-white"><strong>Booking details</strong></div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item bg-white">Start date: <%= @booking.start_date.strftime("%d/%m/%Y") %></li>
                <li class="list-group-item bg-white">End date: <%= @booking.end_date.strftime("%d/%m/%Y") %></li>
                <% if @booking.status == "Pending" %>
                  <li class="list-group-item bg-white color-pending">Status: <strong><%= @booking.status %></strong></li>
                <% elsif @booking.status == "Accepted" %>
                  <li class="list-group-item bg-white color-accepted">Status: <strong><%= @booking.status %></strong></li>
                <% elsif @booking.status == "Rejected" %>
                  <li class="list-group-item bg-white color-rejected">Status: <strong><%= @booking.status %></strong></li>
                <% end %>
                <li class="list-group-item bg-white">Booking total price: <i class="fa-solid fa-euro-sign"></i> <%= @booking.total_price.round() %></li>
              </ul>
            </div>
            <%= link_to booking_path(@booking), data: {turbo_method: :delete, turbo_confirm: "Do you want to delete this booking?"} do %>
            <i class="fa-solid fa-xmark delete-button color-red"></i>
            <% end %>
          </div>
          <a class="blue-button" id="back-dash-bookings" href="/dashboard#bookings-tab">Back</a>
      </div>
  </div>
</div>

<%# <script>
  const testLink = document.getElementById("back-dash-bookings");
  testLink.addEventListener("click", () => {
    const targetHash = "#" + (testLink.href.split("#")[1]);
    window.location.hash = targetHash;
  })
</script> %>