config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  resources :items, only: [:index, :show, :new, :create, :update, :destroy] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:show, :destroy] do
    member do
      post :accept
      post :reject
    end
  end

  get "/my_booked_items/:id", to: "bookings#booked_items_show", as: :my_booked_item

  get "/dashboard", to: "bookings#dashboard"

end

app/views/pages/home.html.erb
<div class="container">
  <!-- <div class="test" style="background-image: url(<%= image_path 'landing-background.jpg' %>)"> -->

  <div class="d-flex justify-content-center">
    <%= link_to items_path, class:"red-button" do %>
      <h4 style="font-size:24px;" class="m-0">Browse all art</h4>
    <% end %>
  </div>

  <h4 class="text-center my-5 text-primary"> Categories </h4>
  <div class="cards">
    <% @categories.each do |category|%>
      <%= link_to items_path(category: category[:name].downcase), class:"text-decoration-none text-white" do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= category[:url] %>)">
      <%= category[:name] %></div>
      <% end %>
    <% end %>
  </div>

  </div>
</div>