config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  resources :items, only: [:index, :show, :new, :create, :update, :destroy] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:show, :destroy] do
    member do
      post :accept
      post :reject
    end
  end

  get "/my_booked_items/:id", to: "bookings#booked_items_show", as: :my_booked_item

  get "/dashboard", to: "bookings#dashboard"

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  #constante utilisée pour la génération des cards de category dans la homepage
  CATEGORY = [
    {name: "Paintings", icon: "fa-solid fa-paintbrush", url: "https://artetpaix.net/modules/homeslider/images/674539d025d637f3d9962eda4ba230879b6784e3_galerie-tableaux-6716-779x448.jpg"},
    {name: "Decoration", icon: "fa-solid fa-jar-wheat", url: "https://www.meublessourice.fr/docs/2/PagesLibres/objets-de-decoration-min.jpg"},
    {name: "Furniture", icon: "fa-solid fa-chair", url: "https://www.starck.fr/00DATA/cms/design/dior/9.jpg"},
    {name: "Sculptures", icon: "fa-solid fa-hammer", url: "https://www.galerie-malaquais.com/fr/oeuvres/thumb/55/m"},
    {name: "Jewels", icon: "fa-regular fa-gem", url: "https://images.unsplash.com/photo-1588444968576-f8fe92ce56fd?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"},
    {name: "Photographs", icon: "fa-solid fa-camera-retro", url: "https://www.myposter.fr/magazin/wp-content/uploads/2019/07/art-black-and-white-black-and-white-21264-scaled.jpg"}
  ]

  #constante utilisée pour la validation du champ category dans le form Items/new
  CATEGORY_NAME = []
  CATEGORY.each do |category|
    CATEGORY_NAME << category[:name]
  end

  validates :category, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def my_items
    @my_items = current_user.items
  end

  def index
    @items = Item.all
    additems = Item.all
    catitems = Item.all
    artitems = Item.all
    tititems = Item.all
    @category = Item::CATEGORY_NAME

    if params[:query].present?
      sql_subquery = "title ILIKE :query
      OR artist ILIKE :query
      OR address ILIKE :query"
      @items = @items.where(sql_subquery, query: "%#{params[:query]}%")

    elsif params[:address].present? || params[:category].present? || params[:artist].present? || params[:title].present?
      (if params[:address].present?
         addquery = "address ILIKE :address"
         additems = @items.where(addquery, address: "%#{params[:address]}%")
       end
       if params[:category].present?
         catquery = "category ILIKE :category"
         catitems = @items.where(catquery, category: "%#{params[:category]}%")
         @default = [params[:category]]
       end
       if params[:artist].present?
         artquery = "artist ILIKE :artist"
         artitems = @items.where(artquery, artist: "%#{params[:artist]}%")
       end
       if params[:title].present?
         titquery = "title ILIKE :title"
         tititems = @items.where(titquery, title: "%#{params[:title]}%")
       end)
      @items = additems & catitems & artitems & tititems

    else
      @items
    end

    @markers = @items.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        map_info_html: render_to_string(partial: "map_info", locals: {item: item}),
        id: item.id
      }
    end
  end

  def show
    @item = Item.find(params[:id])
    @booking = Booking.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save
      redirect_to item_path(@item), notice: 'Item was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: 'Item was successfully destroyed.'
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :category, :artist, :address, photos: [])
  end

end

app/views/items/_cards_index.html.erb
<div class="row">

        <% @items.each do |item|%>

          <div class="col-md-4">

            <div style="height: 425px">

              <div class="flat-card mt-3">

                <div class="flat-card-image">
                  <%= link_to item_path(item) do %>
                    <div class="image-container">
                      <% item.photos.each do |photo| %>
                        <%= cl_image_tag photo.key, class: "img-fluid", crop: :fill %>
                      <% end %>
                    </div>
                  <% end %>
                </div>

                <div class="flat-card-content">
                  <%= link_to item_path(item) do %>
                    <div class="d-flex flex-column justify-content-between h-100">
                      <div class="flat-card-title border-bottom">
                        <h4 style="font-size: 20px" class="color-blue">
                        <strong><%= item.title %></strong></h4>
                      </div>

                      <p style="font-size: 16px" class="color-blue pt-2">Artist: <%= item.artist %></p>
                      <p style="font-size: 14px" class="color-blue">Address: <%= item.address %></p>

                      <div class="flex justify-content-between">
                        <div class="flex align-items-center thick-underline">
                          <p class="color-blue m-0">
                            <i class="<%= Item::CATEGORY[Item::CATEGORY_NAME.index(item.category)][:icon] %>"></i>
                            <span ><%= item.category %></span>
                          </p>
                        </div>

                        <div class="flex align-items-center ms-3 thick-underline">
                          <p class="color-blue m-0">
                            <i class="fa-solid fa-euro-sign"></i>
                            <span><strong><%= item.price.round() %></strong> / day </span>
                          </p>
                        </div>
                      </div>
                    </div>
                  <% end  %>
                </div>

                <div class="flat-card-actions" style="padding-top:9px;">
                  <p data-controller="toggle-favorite" data-action="click->toggle-favorite#fire" class="color-blue">
                    <i data-toggle-favorite-target="togglableElement" class="fa-regular fa-heart color-red"></i>
                    <i data-toggle-favorite-target="togglableItem" class="fa-solid fa-heart d-none color-red"></i>
                    Add to favorites
                  </p>
                </div>

              </div>
            </div>

          </div>

        <% end %>

      </div>

app/views/items/_category_filters.html.erb
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-8 text-center">

        <div class="d-flex flex-wrap justify-content-center pb-4" data-controller="categoryselector" data-action="click->categoryselector#active">

            <div class="clickable category" >
              <small style="font-size:12px;" data-categoryselector-target="categoryItem">Paintings</small>
            </div>

        </div>
      </div>
    </div>
  </div>

app/views/items/_edit_form.html.erb
<%= simple_form_for(item) do |f| %>
  <%= f.input :title, label: false, placeholder: "Title" %>
  <%= f.input :artist, label: false, placeholder: "Artist" %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.input :description, label: false, placeholder: "Description" %>
  <%= f.input :category, collection: Item::CATEGORY_NAME %>
  <%= f.input :price, label: false, placeholder: "Price" %>
  <%= f.input :address, label: false, placeholder: "Address" %>
  <%= f.submit class:'red-button' %>
<% end %>

app/views/items/_form.html.erb
<%= simple_form_for(item, html: {multipart: true}) do |f| %>
  <div>
    <%= f.input :title, label: false, placeholder: "Title", input_html: { class: "bg-white" } %>
    <%= f.input :artist, label: false, placeholder: "Artist", input_html: { class: "bg-white" } %>
    <%= f.input :photos, as: :file, input_html: { multiple: true, class: "bg-white" } %>
    <%= f.input :description, label: false, placeholder: "Description", input_html: { class: "bg-white" } %>
    <%= f.input :category, collection: Item::CATEGORY_NAME, input_html: { class: "bg-white" } %>
    <%= f.input :price, label: false, placeholder: "Price", input_html: { class: "bg-white" } %>
    <%= f.input :address, label: false, placeholder: "Address", input_html: { class: "bg-white" } %>
  </div>
  <div>
    <%= f.submit class: 'red-button' %>
  </div>
<% end %>

app/views/items/_map.erb
  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Show / Hide map
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <%# Map html to insert below %>
          <div class="row">
            <div class="col-md-12 d-flex justify-content-center map-box">
              <div class="map" style="width: 100%; height: 100%;"
                data-controller="map"
                data-map-markers-value="<%= @markers.to_json %>"
                data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
            </div>
          </div>
          <%# Map html to insert above %>
        </div>
      </div>
    </div>
  </div>

app/views/items/_map.html.erb
  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button white-box bold-text" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Show / Hide map
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body white-box">
          <%# Map html to insert below %>
          <div class="row">
            <div class="col-md-12 d-flex justify-content-center map-box">
              <div class="map" style="width: 100%; height: 100%;"
                data-controller="map"
                data-map-markers-value="<%= @markers.to_json %>"
                data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
            </div>
          </div>
          <%# Map html to insert above %>
        </div>
      </div>
    </div>
  </div>

app/views/items/_map_info.html.erb
<div>
  <% item.photos.each do |photo| %>
    <%= cl_image_tag photo.key, class: "img-fluid", crop: :fill %>
  <% end %>
  <h5 class="my-3"><%= item.title %></h5>
</div>

app/views/items/_multi_search_bar.erb
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: items_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :address,
          params[:address],
          class: "form-control mx-1",
          placeholder: "Location"
        %>
        <%= text_field_tag :category,
          params[:category],
          class: "form-control mx-1",
          # style: "width:150px",
          placeholder: "Category"
        %>
        <%#= select_tag :category,
          options_for_select(@category, selected: @default),
          class: "form-control mx-1",
          placeholder: params[:category].present? ? params[:category] : "Select category"
        %>
        <%= text_field_tag :artist,
          params[:artist],
          class: "form-control  mx-1",
          placeholder: "Artist"
        %>
        <%= text_field_tag :title,
          params[:title],
          class: "form-control  mx-1",
          placeholder: "Name"
        %>

        <%= submit_tag "Search", name: "", class: "btn btn-primary text-white" %>
      <% end %>
    </div>
  </div>

app/views/items/_multi_search_bar.html.erb
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: items_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :address,
          params[:address],
          class: "form-control mx-1 bg-white",
          placeholder: "Location"
        %>
        <%= text_field_tag :category,
          params[:category],
          class: "form-control mx-1 bg-white",
          # style: "width:150px",
          placeholder: "Category"
        %>
        <%#= select_tag :category,
          options_for_select(@category, selected: @default),
          class: "form-control mx-1",
          placeholder: params[:category].present? ? params[:category] : "Select category"
        %>
        <%= text_field_tag :artist,
          params[:artist],
          class: "form-control mx-1 bg-white",
          placeholder: "Artist"
        %>
        <%= text_field_tag :title,
          params[:title],
          class: "form-control mx-1 bg-white",
          placeholder: "Name"
        %>

        <%= submit_tag "Search", class: "ms-5 red-button" %>
      <% end %>
    </div>
  </div>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="container">

  <h4 class="text-center mt-5"> <strong>Find the perfect fit for your interior!</strong></h4>

  <%= render "multi_search_bar" %>

  <%#= render "category_filters" %>

  <%= render "map" %>

  <%= render "cards_index" %>

</div>

app/views/items/my_items.html.erb
<div class="container mt-3">
  <h1>My Items</h1>
  <div id="create-btn" class="btn btn-primary">
    <%= link_to 'Add new item', new_item_path %>
  </div>

  <% if @my_items.any? %>
    <div class="my-items-grid">
      <% @my_items.each do |item| %>
        <div class="my-item-card mt-3">
          <div class="my-item-card-title">
            <h3><%= link_to item.title, item %></h3>

          </div>

          <div class="my-item-card-description">
            <%= item.description %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>You don't have any items yet.</p>
  <% end %>
  <%= link_to 'Back', items_path, class:"btn btn-secondary" %>
</div>

app/views/items/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new Item</h1>
        <div class="mt-3">
          <%= render "form", item: @item %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class='mt-3'>
  <div class='card-product card-height-modifier d-flex'>
    <div class="image-container me-5"> <!-- Previously me-5 -->
      <% @item.photos.each do |photo| %>
      <%= cl_image_tag photo.key, class: "img-fluid", crop: :fill %>
      <% end %>
    </div>
    <div class='card-product-infos flex-grow-1'>
      <div>
        <h2 class="card-title color-blue"><%=@item.title.capitalize%></h2>
        <p class="artist-show-display thick-underline bold-text color-blue"><%=@item.artist.capitalize%></p>
        <p class="my-3"><%=@item.description.capitalize %></p>
        <p class="m-0 pb-0 thick-underline"></p>
        <div class="flex align-items-center color-blue">
          <p style="width: 90px" class="mt-3 mb-0 bold-text card-content-opacity">Price: </p>
          <p class="mt-3 mb-0 bold-text card-content-opacity"><i class="fa-solid fa-euro-sign"></i> <%= @item.price.round() %> / day</p>
        </div>
        <div class="flex align-items-center color-blue">
          <p style="width: 90px" class="mt-3 mb-0">Owner: </p>
          <p class="mt-3 mb-0"><%=@item.user.first_name%> <%=@item.user.last_name%></p>
        </div>
        <div class="flex align-items-center color-blue">
          <p style="width: 90px" class="mt-3 mb-0">Address: </p>
          <p class="mt-3 mb-0"><%=@item.address%></p>
        </div>
      </div>
    </div>
  </div>

  <div class='card mb-4 pb-3 bg-white shadow'>

    <%# Affichage du bouton delete et du formulaire d'édition de l'oeuvre si l'utilisateur connecté correspond au propriétaire %>
    <% if current_user && @item.user == current_user %>
      <div class='card-body bg-white px-4'>
        <div class="d-flex justify-content-between">
          <%= link_to 'Delete', item_path(@item), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"red-button" %>
        </div>
      </div>
      <div class="col-6 p-4 pt-0 bg-white">
        <div class="p-3 blue-card-border">
          <h3 class="border-bottom mb-3">Edit item</h3>
          <%= render 'edit_form', item: @item %>
        </div>
      </div>
      <%# Affichage du formulaire de réservation si l'utilisateur connecté ne correspond pas au propriétaire %>
      <% elsif current_user && @item.user != current_user %>
        <div class="col-6 p-4 bg-white">
          <div class="p-3 blue-card-border">
            <h3 class="border-bottom mb-3 pb-2">Book the item</h3>
            <h4 class="text-muted">Please select dates to check availability</h4>
            <%= render 'bookings/form', item: @item, booking: @booking %>
          </div>
        </div>
      <% end %>
    <div class="col-4 px-4 py-3 bg-white">
      <%= link_to 'Back', :back, class:"blue-button" %>
    </div>
  </div>


</div>