config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  resources :items, only: [:index, :show, :new, :create, :update, :destroy] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:show, :destroy] do
    member do
      post :accept
      post :reject
    end
  end

  get "/my_booked_items/:id", to: "bookings#booked_items_show", as: :my_booked_item

  get "/dashboard", to: "bookings#dashboard"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeasArt</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">

      <nav class="navbar-lewagon">
        <div class="navbar-elements">
          <%= link_to root_path do %>
            <%= image_tag "logo.png", alt: "logo", width: 120 %>
          <% end %>
          <div data-controller="dropdown-navbar" class="menu-container">
            <div class="menu-button" data-action="click->dropdown-navbar#click">
              <div class="menu-icons">
                <span><i class="fa-solid fa-bars navbar-menu"></i></span>
                <span><i class="fa-solid fa-user navbar-user"></i></span>
              </div>
            </div>
            <% unless user_signed_in? %>
              <div class="togglable-menu d-none disconnected" data-dropdown-navbar-target="togglableMenu">
                <%= link_to 'Log in', new_user_session_path, class:"menu-actions" %>
                <%= link_to 'Create account', new_user_registration_path, class:"menu-actions" %>
              </div>
            <% else %>
              <div class="togglable-menu d-none logged" data-dropdown-navbar-target="togglableMenu">
                <%= link_to 'Edit profile', edit_user_registration_path, class:"menu-actions actions-signed-in" %>
                <%= link_to 'My dashboard', dashboard_path, class:"menu-actions actions-signed-in" %>
                <%= link_to 'Log out', destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Do you want to log out?"}, class:"menu-actions actions-signed-in" %>
              </div>
            <% end %>
          </div>
        </div>
      </nav>

      <div class="main-content">
        <div class="inner-content">
          <div class="container">
            <% unless notice.nil? %>
              <p class="alert alert-success m-0"><%= notice %></p>
            <% end %>
            <% unless alert.nil? %>
              <p class="alert alert-danger m-0"><%= alert %></p>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>

      <footer class="footer border-top">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      </footer>

    </div>
  </body>
</html>